% Automatically generated by Supertag.tcl on Thu 05 Nov 2015

sent(1, A) :-
     prob_parse([
       si('Quand', kon, 'Quand', [dr(0,dr(0,s,s),s)-0.71138, dr(0,s,s)-0.275582 ]),
       si('Jean', nam:hs, 'Jean', [np-0.995956 ]),
       si('aime', ver:pres, 'aimer', [dr(0,dl(0,np,s),np)-0.865549 ]),
       si('Marie', nam:fs, 'Marie', [np-0.981645 ]),
       si(',', pun, ',', [let-0.546621, dr(0,dl(0,s,s),s)-0.309411 ]),
       si('il', pro:per, 'il', [np-1 ]),
       si('deteste', ver:pres, 'deteste', [dr(0,dl(0,np,s),np)-0.819554 ]),
       si('Pierre', nam:ms, 'Pierre', [np-0.929457 ])
     ], A).
